name: Publish to chrome web store
on:
  push:
jobs:
  zip-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Zip
        run: |
          cd app
          zip -r ../dist.zip .
          cd ..
          ls
      - uses: Klemensas/chrome-extension-upload-action@$VERSION
        with:
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          file-name: './dist.zip'
          app-id: 'ndpmhjnlfkgfalaieeneneenijondgag'
          publish: true