name: Publish to chrome web store
jobs:
  zip-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Zip
        run: |
          zip -r dist.zip app/*
      - name: Upload & release
        uses: zpix1/chrome-extension-upload@1.1.2
        with:
          file-path: dist.zip
          extension-id: ndpmhjnlfkgfalaieeneneenijondgag
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
